spring.application.name=proyectoBancosol
# Configuracion para encontrar los JSPs
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# Configuracion basica de la base de datos
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/bancosol_db
spring.datasource.username=root
spring.datasource.password=Cacaroja22
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Importante para que no borre tus tablas si usas el script SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
